content:
  source:
    dockerfile: Dockerfile.rhel7
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/machine-config-operator.git
      web: https://github.com/openshift/machine-config-operator
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-9-golang-ci-build-root
enabled_repos:
- rhel-9-baseos-rpms
- rhel-9-appstream-rpms
- rhel-9-server-ose-rpms-embargoed
for_payload: true
from:
  builder:
  - stream: rhel-9-golang
  member: openshift-enterprise-base-rhel9
name: openshift/ose-machine-config-operator
owners:
- acrawfor@redhat.com
- imcleod@redhat.com
- runcom@redhat.com
- smilner@redhat.com
